version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: leadbro_frontend
    ports:
      - '3003:3000'
    volumes:
      - './:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
